### ISSUE TITLE
Standard cookie parsing

### ISSUE THREAD

**Issue by CrowdHailer** [princemaple/cookie_jar#2]
Hi, 

I have just stared working on this hex package [cookie](https://hex.pm/packages/cookie) it is a port of the functionality found in plug. So despite having a 0.1.0 version it should be quite stable (I hope to push to releasing a v1.0 soon) As cookie functionality is required both server side and client side it seamed like a library that would be useful to extract. (I intend to start using it it my tokumei framework).

If you are interested in integrating it's use into cookie_jar ping me if there are any issues and hopefully we can get a nice approach to cookies in Elixir

**Comment by princemaple** [comment]
Hi, thanks for the information.

I'm a little confused. Why is the repo named Raxx?

A utility lib that encapsulates all possible manipulations around cookie sounds like a good lib idea, but using a generic name as the lib name is not. Just saying.

Best of luck in making a new framework.

Po

**Comment by princemaple** [comment]
Regarding cookie parsing, cookie jar is more a hacking tool. It doesn't care about anything but the content of the cookie returned from the server. It serves as a cache that preserves the cookies for later requests. The minimum implementation of cookie parsing is only to aid hijacking all the useful information. I don't see it ever needing a proper parsing functionality in the foreseeable future. Thank you very much for letting me know about your new library, though. I'll close this now. Definitely let me know if you think otherwise in any aspects.

**Comment by CrowdHailer** [comment]
Cheers for getting back,

I should probably move the code into it's own repo. It has been living in the same repository to make my life easier through the development process but that should be over soon.

Regarding cookie_jar it looked like your implementation was quite simple. I.e. you don't try and simulate only sending the right cookies to the right domain etc. If that is the end scope for cookie jar then I agree you don't need an extra dependency.

**Comment by princemaple** [comment]
:+1:
