### ISSUE TITLE
Are you amenable to help?

### ISSUE THREAD

**Issue by scohen** [princemaple/cookie_jar#23]
Someone asked about this library in the Elixir discord yesterday and in checking it out I found a couple of issues. 

For example, the `CookieJar.Server` module will emit all cookies to all requests, ignoring HTTPOnly, path and expiry cookie attributes.  Also, if there is only one `CookieJar.Server`, in an app, it will emit cookies from one domain into another.

I was going to work on fixing the above and other issues, but it will likely result in an incompatible API (which could be put in a different module) and was wondering if you would be open to this type of pull request.

**Comment by princemaple** [comment]
Hi Steve, yes I'm happy to see this kind of PR. If the API is going to be different, we can have a new module that specifically respects the standards. Or, by default, it does that, and we can have a forced mode that ignores or standards. After all, the initial reason I made this was to "hack" things. That's why it didn't need to parse those things. If people started using this for more general purposes, I'm all for it.

**Comment by scohen** [comment]
Thanks for the prompt reply. I'll have something soon.

**Comment by princemaple** [comment]
Cheers. Looking forward to that!
